name: Git Workflow Simulator CI

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verify Python Installation
        run: python --version

      - name: Run Application
        run: python MiniProject-02-Git-Workflow-Simulator/app.py
